services:
  # Backend Web Service (serves both API and frontend)
  - type: web
    name: ai-teacher-backend
    runtime: docker
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: audio-storage
      mountPath: /app/static/audio
      sizeGB: 1

 