services:
  # Backend Web Service
  - type: web
    name: ai-teacher-backend
    runtime: docker
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: audio-storage
      mountPath: /app/static/audio
      sizeGB: 1

  # Frontend Static Site
  - type: static
    name: ai-teacher-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-teacher-backend
          envVarKey: RENDER_EXTERNAL_URL 